---
- name: Check and deploy Docker container
  hosts: QA
  become: true

  tasks:
    - name: Check if container is running
      command: docker ps -q --filter "name=addressbook"
      register: container_check
      failed_when: false
      changed_when: false

    - name: Stop and remove container if running
      command: docker rm -f addressbook
      when: container_check.stdout != ""
    
    - name: Remove image if exists
      command: docker pull maclean23/address-book
      ignore_errors: true

    - name: Deploy new container
      command: docker run -itd -p 7000:8080 --name addressbook maclean23/address-book
